// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SECompass.DataAccess.DbContexts;

#nullable disable

namespace SECompass.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612173559_AddPublicPortfolio")]
    partial class AddPublicPortfolio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SECompass.DataAccess.Entities.CareerRoadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CareerRoadmapId");

                    b.Property<Guid>("CareerRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CareerRoleId");

                    b.ToTable("CareerRoadmaps", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.CareerRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CareerRoleId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CareerRoles", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ChatMessageId");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ChatSessionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.GitHubRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GithubRepositoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("GitHubRepositories", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.JobScrapingSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobScrapingSettingId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobScrapingSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = "Sunday",
                            Enabled = true,
                            Frequency = "Weekly",
                            TimeOfDay = "00:00:00"
                        });
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.JobScrapingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobScrapingSourceId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("JobCardXPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaxPostings")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TagsXPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TitleXPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("JobScrapingSources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            JobCardXPath = "//li[contains(@class,'jobs-search')] | //div[contains(@class,'job-search-card')]",
                            MaxPostings = 40,
                            Name = "LinkedIn",
                            Region = "Global",
                            TagsXPath = ".//*[contains(@class,'metadata')] | .//*[contains(@class,'subtitle')]",
                            TitleXPath = ".//h3 | .//*[contains(@class,'title')]",
                            Url = "https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=software%20engineer&location=Vietnam&start=0"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            JobCardXPath = "//li[contains(@class,'job-item')]",
                            MaxPostings = 40,
                            Name = "CareerLink",
                            Region = "Vietnam",
                            TagsXPath = ".//a[contains(@class,'job-position')]",
                            TitleXPath = ".//h5[contains(@class,'job-name')]",
                            Url = "https://www.careerlink.vn/viec-lam/cntt-phan-mem/19"
                        });
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.JobTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobTrendId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TechSkill")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrendScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobTrends", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.LearningResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LearningResourceId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("LearningResources", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NodeId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.NodeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NodeProgressId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonalRoadmapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoadmapNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapNodeId");

                    b.HasIndex("PersonalRoadmapId", "RoadmapNodeId")
                        .IsUnique();

                    b.ToTable("NodeProgresses", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.NodeTechnicalSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NodeTechnicalSkillId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechnicalSkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalSkillId");

                    b.HasIndex("NodeId", "TechnicalSkillId")
                        .IsUnique();

                    b.ToTable("NodeTechnicalSkills", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.PersonalRoadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PersonalRoadmapId");

                    b.Property<Guid>("CareerRoadmapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CareerRoadmapId");

                    b.HasIndex("ProfileId");

                    b.ToTable("PersonalRoadmaps", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BioDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudiedYear")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.ProfileTechnicalSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProfileTechnicalSkillId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechnicalSkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalSkillId");

                    b.HasIndex("ProfileId", "TechnicalSkillId")
                        .IsUnique();

                    b.ToTable("ProfileTechnicalSkills", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.PublicPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CachedPortfolioAnalysisJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headline")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicBio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("PublicPortfolios", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.RoadmapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoadmapNodeId");

                    b.Property<Guid>("CareerRoadmapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Topic");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentRoadmapNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PositionX")
                        .HasColumnType("int");

                    b.Property<int?>("PositionY")
                        .HasColumnType("int");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Required");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ParentRoadmapNodeId");

                    b.HasIndex("CareerRoadmapId", "NodeId")
                        .IsUnique();

                    b.ToTable("RoadmapNodes", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.RoadmapNodeEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoadmapNodeEdgeId");

                    b.Property<Guid>("CareerRoadmapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Next");

                    b.Property<Guid>("FromRoadmapNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToRoadmapNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FromRoadmapNodeId");

                    b.HasIndex("ToRoadmapNodeId");

                    b.HasIndex("CareerRoadmapId", "FromRoadmapNodeId", "ToRoadmapNodeId", "EdgeType")
                        .IsUnique();

                    b.ToTable("RoadmapNodeEdges", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.TechnicalSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TechnicalSkillId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TechnicalSkills", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHashed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@secompass.com",
                            FullName = "Admin Administrator",
                            IsActive = true,
                            PasswordHashed = "$2b$12$x60evDbGMbtCfCLsHPITg.F90EITs5NYkcp/zoKMuwzsZ3TRcqBHK",
                            Role = 0
                        });
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserRefreshTokenId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.CareerRoadmap", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.CareerRole", "CareerRole")
                        .WithMany("CareerRoadmaps")
                        .HasForeignKey("CareerRoleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CareerRole");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.ChatMessage", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.ChatSession", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.Profile", "Profile")
                        .WithMany("ChatSessions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.GitHubRepository", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.Profile", "Profile")
                        .WithMany("GitHubRepositories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.LearningResource", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.Node", "Node")
                        .WithMany("LearningResources")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.Node", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.Node", "ParentNode")
                        .WithMany("Children")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.NodeProgress", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.PersonalRoadmap", "PersonalRoadmap")
                        .WithMany("NodeProgresses")
                        .HasForeignKey("PersonalRoadmapId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.RoadmapNode", "RoadmapNode")
                        .WithMany("NodeProgresses")
                        .HasForeignKey("RoadmapNodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("PersonalRoadmap");

                    b.Navigation("RoadmapNode");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.NodeTechnicalSkill", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.Node", "Node")
                        .WithMany("NodeTechnicalSkills")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.TechnicalSkill", "TechnicalSkill")
                        .WithMany("NodeTechnicalSkills")
                        .HasForeignKey("TechnicalSkillId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("TechnicalSkill");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.PersonalRoadmap", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.CareerRoadmap", "CareerRoadmap")
                        .WithMany("PersonalRoadmaps")
                        .HasForeignKey("CareerRoadmapId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.Profile", "Profile")
                        .WithMany("PersonalRoadmaps")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CareerRoadmap");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.Profile", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SECompass.DataAccess.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.ProfileTechnicalSkill", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.Profile", "Profile")
                        .WithMany("ProfileTechnicalSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.TechnicalSkill", "TechnicalSkill")
                        .WithMany("ProfileTechnicalSkills")
                        .HasForeignKey("TechnicalSkillId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("TechnicalSkill");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.PublicPortfolio", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.Profile", "Profile")
                        .WithOne("PublicPortfolio")
                        .HasForeignKey("SECompass.DataAccess.Entities.PublicPortfolio", "ProfileId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.RoadmapNode", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.CareerRoadmap", "CareerRoadmap")
                        .WithMany("RoadmapNodes")
                        .HasForeignKey("CareerRoadmapId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.Node", "Node")
                        .WithMany("RoadmapNodes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.RoadmapNode", "ParentRoadmapNode")
                        .WithMany("Children")
                        .HasForeignKey("ParentRoadmapNodeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("CareerRoadmap");

                    b.Navigation("Node");

                    b.Navigation("ParentRoadmapNode");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.RoadmapNodeEdge", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.CareerRoadmap", "CareerRoadmap")
                        .WithMany("RoadmapNodeEdges")
                        .HasForeignKey("CareerRoadmapId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.RoadmapNode", "FromRoadmapNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromRoadmapNodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SECompass.DataAccess.Entities.RoadmapNode", "ToRoadmapNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToRoadmapNodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CareerRoadmap");

                    b.Navigation("FromRoadmapNode");

                    b.Navigation("ToRoadmapNode");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("SECompass.DataAccess.Entities.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.CareerRoadmap", b =>
                {
                    b.Navigation("PersonalRoadmaps");

                    b.Navigation("RoadmapNodeEdges");

                    b.Navigation("RoadmapNodes");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.CareerRole", b =>
                {
                    b.Navigation("CareerRoadmaps");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.Node", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("LearningResources");

                    b.Navigation("NodeTechnicalSkills");

                    b.Navigation("RoadmapNodes");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.PersonalRoadmap", b =>
                {
                    b.Navigation("NodeProgresses");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.Profile", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("GitHubRepositories");

                    b.Navigation("PersonalRoadmaps");

                    b.Navigation("ProfileTechnicalSkills");

                    b.Navigation("PublicPortfolio");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.RoadmapNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("IncomingEdges");

                    b.Navigation("NodeProgresses");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.TechnicalSkill", b =>
                {
                    b.Navigation("NodeTechnicalSkills");

                    b.Navigation("ProfileTechnicalSkills");
                });

            modelBuilder.Entity("SECompass.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("UserRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
