// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SECompass.DataAccess.DbContexts;

#nullable disable

namespace SECompass.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612120000_AdminSeedAndRemoveItviec")]
    partial class AdminSeedAndRemoveItviec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
